import { msg } from '@lingui/core/macro';

import { type WebsiteRoute } from './website-route';
import { PRODUCT_BRANDING } from 'twenty-shared/constants';

export const STATIC_WEBSITE_ROUTES: readonly WebsiteRoute[] = [
  {
    changeFrequency: 'weekly',
    description: msg`The modern CRM platform for growing teams. Modular, scalable, and built to fit your business.`,
    id: 'home',
    indexed: true,
    path: '/',
    priority: 1,
    title: msg`${PRODUCT_BRANDING.name} | modern CRM platform`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Extend ${PRODUCT_BRANDING.name} with vetted apps — call recording, enrichment, Slack, Linear and more. Install any app on your modern CRM workspace in one click.`,
    id: 'apps',
    indexed: false,
    path: '/apps',
    priority: 0.8,
    title: msg`${PRODUCT_BRANDING.name} Apps — Vetted Apps for the modern CRM`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Pipelines, custom objects, AI assistants, and a native API on top of Postgres. ${PRODUCT_BRANDING.name} is the modern CRM with the modern UX teams actually want to use.`,
    id: 'product',
    indexed: true,
    path: '/product',
    priority: 0.8,
    title: msg`${PRODUCT_BRANDING.name} Features — Modern CRM Platform`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Cloud Pro starts at $9/user/month with unlimited custom objects. Self-host the open source core for free, or upgrade to Organization for SSO and row-level permissions.`,
    id: 'pricing',
    indexed: true,
    path: '/pricing',
    priority: 0.9,
    title: msg`${PRODUCT_BRANDING.name} Pricing — Plans from $9 per User per Month`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`HubSpot gates custom objects behind its $150/seat Enterprise tier. See the full price comparison, with sources, and what ${PRODUCT_BRANDING.name} includes from $9 per user.`,
    id: 'comparePricingHubspot',
    indexed: false,
    path: '/compare-pricing/hubspot',
    priority: 0.7,
    title: msg`${PRODUCT_BRANDING.name} vs HubSpot Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Sales Cloud Enterprise lists at $175/user/month before support, sandboxes, and AI add-ons. Compare the real cost with ${PRODUCT_BRANDING.name}, from $9 per user.`,
    id: 'comparePricingSalesforce',
    indexed: false,
    path: '/compare-pricing/salesforce',
    priority: 0.7,
    title: msg`${PRODUCT_BRANDING.name} vs Salesforce Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`SAP Sales Cloud lists at $134/user/month before a year-one implementation project that often exceeds the licenses. Compare with ${PRODUCT_BRANDING.name}, from $9 per user.`,
    id: 'comparePricingSap',
    indexed: false,
    path: '/compare-pricing/sap-sales-cloud',
    priority: 0.7,
    title: msg`${PRODUCT_BRANDING.name} vs SAP Sales Cloud Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Pipedrive caps automations per company and keeps SSO for its top tier. Compare real per-seat costs with ${PRODUCT_BRANDING.name}, from $9 per user with no caps.`,
    id: 'comparePricingPipedrive',
    indexed: false,
    path: '/compare-pricing/pipedrive',
    priority: 0.7,
    title: msg`${PRODUCT_BRANDING.name} vs Pipedrive Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Dynamics 365 Sales runs $105/user/month plus $40/GB database storage. See the full comparison with ${PRODUCT_BRANDING.name}, from $9 per user, open source.`,
    id: 'comparePricingDynamics',
    indexed: false,
    path: '/compare-pricing/microsoft-dynamics',
    priority: 0.7,
    title: msg`${PRODUCT_BRANDING.name} vs Microsoft Dynamics Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Tell us what you need and get matched with a certified ${PRODUCT_BRANDING.name} partner in 48 hours, or browse the directory of agencies and consultants who migrate, customise, and operate the modern CRM.`,
    id: 'partners',
    indexed: false,
    path: '/partners',
    priority: 0.7,
    title: msg`Find a ${PRODUCT_BRANDING.name} Partner — Certified modern CRM Experts`,
  },
  {
    // The application form: noindex (a utility route, excluded from the
    // sitemap by getIndexedWebsiteRoutes), reachable from the partner CTAs.
    changeFrequency: 'yearly',
    description: msg`Apply to join the ${PRODUCT_BRANDING.name} partner ecosystem and grow your practice with the #1 modern CRM.`,
    id: 'partnersApply',
    indexed: false,
    path: '/partners/apply',
    priority: 0.3,
    title: msg`Become a ${PRODUCT_BRANDING.name} Partner — Apply`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Join the ${PRODUCT_BRANDING.name} partner ecosystem: implement, migrate, and support the #1 modern CRM, and grow your practice with the teams building it.`,
    id: 'partnersBecome',
    indexed: false,
    path: '/partners/become',
    priority: 0.6,
    title: msg`Become a ${PRODUCT_BRANDING.name} Partner — Join the modern CRM Ecosystem`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Submit a project brief and get matched with a certified ${PRODUCT_BRANDING.name} partner for migration, customisation, and CRM implementation.`,
    id: 'partnersBrief',
    indexed: false,
    path: '/partners/brief',
    priority: 0.3,
    title: msg`Submit a Client Brief — ${PRODUCT_BRANDING.name} Partners`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Packaged CRMs make every company look the same. ${PRODUCT_BRANDING.name} is the modern CRM teams shape around their workflow, with a modern UI and a developer-first platform.`,
    id: 'whyTwenty',
    indexed: false,
    path: '/why-twenty',
    priority: 0.8,
    title: msg`Why ${PRODUCT_BRANDING.name} — The modern CRM Built to Be Customised`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Every new release of ${PRODUCT_BRANDING.name}, the modern CRM platform, with changelogs, demos, and the highlights teams care about most.`,
    id: 'releases',
    indexed: false,
    path: '/releases',
    priority: 0.7,
    title: msg`${PRODUCT_BRANDING.name} Releases — What's New in the modern CRM`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Real customer stories from teams running their business on ${PRODUCT_BRANDING.name}: how they migrated, what they customised, and what changed once their CRM finally fit.`,
    id: 'customers',
    indexed: false,
    path: '/customers',
    priority: 0.7,
    title: msg`${PRODUCT_BRANDING.name} Customers — How Modern Teams Run Their CRM`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`How ${PRODUCT_BRANDING.name} collects, uses, and protects your data — our GDPR- and CCPA-compliant privacy policy.`,
    id: 'privacyPolicy',
    indexed: false,
    path: '/privacy-policy',
    priority: 0.3,
    title: msg`Privacy Policy | ${PRODUCT_BRANDING.name}`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`The terms governing your use of ${PRODUCT_BRANDING.name} and its modern CRM services.`,
    id: 'terms',
    indexed: false,
    path: '/terms',
    priority: 0.3,
    title: msg`Terms of Service | ${PRODUCT_BRANDING.name}`,
  },
  {
    // Post-checkout license activation: noindex (a utility route reached only
    // with a Stripe ?session_id=, excluded from the sitemap).
    changeFrequency: 'yearly',
    description: msg`Activate your ${PRODUCT_BRANDING.name} enterprise license after checkout and copy your key into your self-hosted instance.`,
    id: 'enterpriseActivate',
    indexed: false,
    path: '/enterprise/activate',
    priority: 0.3,
    title: msg`Enterprise Activation | ${PRODUCT_BRANDING.name}`,
  },
  {
    // The interactive halftone generator: an internal dev tool, noindex and
    // excluded from the sitemap (getIndexedWebsiteRoutes). Mounted client-only.
    changeFrequency: 'monthly',
    description: msg`Interactive halftone generator exported from ${PRODUCT_BRANDING.name}.`,
    id: 'halftone',
    indexed: false,
    path: '/halftone',
    priority: 0,
    title: msg`Halftone Generator | ${PRODUCT_BRANDING.name}`,
  },
];
